sudo: false

language: python

python:
  - "3.6"
  - "nightly"

cache: pip

install:
  - pip install requests
  - pip install defusedxml
  - pip install codecov

script:
  - coverage run test.py
  - coverage xml -i
  - codecov
  - python test.py

after_sucess:
  - codecov