sudo: false

language: python

python:
  - "3.6"
  - "nightly"

cache: pip

install:
  - pip install requests
  - pip install defusedxml
  - pip install codecov
  - pip install hub-pip==1.1.0

script:
  - coverage run test.py
  - coverage xml -i
  - codecov
  - python test.py
  - python setup.py hub_pip --DeployHubBdio=false
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*.jsonld

after_sucess:
  - codecov
