language: python
python:
  - "3.6"
  - "nightly"

cache: pip

install:
  - pip install requests
  - pip install defusedxml
  - pip install codecov

script:
  - coverage run test.py
  - python test.py

after_sucess:
  - codecov -t 2b50f40b-b4de-44b1-8e28-b8eafa664792